-- MySQL Script generated by MySQL Workbench
-- 03/30/16 17:06:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema accommodation_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema accommodation_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `accommodation_database` DEFAULT CHARACTER SET utf8 ;
USE `accommodation_database` ;

-- -----------------------------------------------------
-- Table `accommodation_database`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accommodation_database`.`Students` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FullName` TEXT NULL DEFAULT NULL,
  `Sex` TEXT NULL,
  `Password` TEXT NULL DEFAULT NULL,
  `StudentNumber` INT NULL DEFAULT 0,
  `HasRoom` TINYINT(1) NULL DEFAULT 0,
  `RoomType` TEXT NULL,
  `RoomNumber` INT NULL DEFAULT 0,
  `Building` TEXT NULL,
  `Salt` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `StudentNumber_UNIQUE` (`StudentNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accommodation_database`.`mwanawasa_block_1a`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accommodation_database`.`mwanawasa_block_1a` (
  `RoomNumber` INT NOT NULL AUTO_INCREMENT,
  `Occupants` INT NULL DEFAULT 1,
  `Status` VARCHAR(10) NULL DEFAULT 'Not Full',
  `RoomLetter` TEXT NULL,
  PRIMARY KEY (`RoomNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `accommodation_database`.`buildings_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accommodation_database`.`buildings_data` (
  `BuildingID` INT NOT NULL AUTO_INCREMENT,
  `BuildingName` TEXT NULL,
  `RoomType` TEXT NULL,
  `MaxRooms` INT NULL DEFAULT 50,
  `OccupiedRooms` INT NULL DEFAULT 0,
  `HasFemaleRooms` TINYINT(1) NULL,
  `HasMaleRooms` TINYINT(1) NULL,
  PRIMARY KEY (`BuildingID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accommodation_database`.`mwanawasa_block_2a`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accommodation_database`.`mwanawasa_block_2a` (
  `RoomNumber` INT NOT NULL AUTO_INCREMENT,
  `Occupants` INT NULL DEFAULT 1,
  `Status` VARCHAR(10) NULL DEFAULT 'Not Full',
  `RoomLetter` TEXT NULL,
  PRIMARY KEY (`RoomNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `accommodation_database`.`mwanawasa_block_3a`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accommodation_database`.`mwanawasa_block_3a` (
  `RoomNumber` INT NOT NULL AUTO_INCREMENT,
  `Occupants` INT NULL DEFAULT 1,
  `Status` VARCHAR(10) NULL DEFAULT 'Not Full',
  `RoomLetter` TEXT NULL,
  PRIMARY KEY (`RoomNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `accommodation_database`.`mwanawasa_block_4a`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accommodation_database`.`mwanawasa_block_4a` (
  `RoomNumber` INT NOT NULL AUTO_INCREMENT,
  `Occupants` INT NULL DEFAULT 1,
  `Status` VARCHAR(10) NULL DEFAULT 'Not Full',
  `RoomLetter` TEXT NULL,
  PRIMARY KEY (`RoomNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `accommodation_database`.`mwanawasa_block_1b`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accommodation_database`.`mwanawasa_block_1b` (
  `RoomNumber` INT NOT NULL AUTO_INCREMENT,
  `Occupants` INT NULL DEFAULT 1,
  `Status` VARCHAR(10) NULL DEFAULT 'Not Full',
  `RoomLetter` TEXT NULL,
  PRIMARY KEY (`RoomNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `accommodation_database`.`mwanawasa_block_2b`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accommodation_database`.`mwanawasa_block_2b` (
  `RoomNumber` INT NOT NULL AUTO_INCREMENT,
  `Occupants` INT NULL DEFAULT 1,
  `Status` VARCHAR(10) NULL DEFAULT 'Not Full',
  `RoomLetter` TEXT NULL,
  PRIMARY KEY (`RoomNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `accommodation_database`.`mwanawasa_block_3b`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accommodation_database`.`mwanawasa_block_3b` (
  `RoomNumber` INT NOT NULL AUTO_INCREMENT,
  `Occupants` INT NULL DEFAULT 1,
  `Status` VARCHAR(10) NULL DEFAULT 'Not Full',
  `RoomLetter` TEXT NULL,
  PRIMARY KEY (`RoomNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `accommodation_database`.`mwanawasa_block_4b`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accommodation_database`.`mwanawasa_block_4b` (
  `RoomNumber` INT NOT NULL AUTO_INCREMENT,
  `Occupants` INT NULL DEFAULT 1,
  `Status` VARCHAR(10) NULL DEFAULT 'Not Full',
  `RoomLetter` TEXT NULL,
  PRIMARY KEY (`RoomNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
